# -*- coding: utf-8 -*-
"""QUICK SORT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kEcW77WsKxvASl_NJdjOXf8MV7X89lhN

# **QUICK SORT**
"""

#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'quickSort' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY arr as parameter.
#

def quickSort(arr):
    p = arr[0]  # First element as pivot
    left = []
    equal = []
    right = []

    for num in arr:
        if num < p:
            left.append(num)
        elif num == p:
            equal.append(num)
        else:
            right.append(num)

    return left + equal + right

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = quickSort(arr)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()