# -*- coding: utf-8 -*-
"""STRING CONSTRUCTION

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TP0MCK3fKsTMsWAM0sAhgV5nHoI2o4MN

# **STRING CONSTRUCTION**
"""

#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'stringConstruction' function below.
#
# The function is expected to return an INTEGER.
# The function accepts STRING s as parameter.
#

def stringConstruction(s):
    char_set = set()
    cost = 0

    for char in s:
        if char not in char_set:
            cost += 1
            char_set.add(char)

    return cost

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    for q_itr in range(q):
        s = input()

        result = stringConstruction(s)

        fptr.write(str(result) + '\n')

    fptr.close()